[facebook_api]
app_id = "706283637471142"
app_secret = "fd67f5083bc4791b06eccf6b08ccf437"
access_token = "EAAKCXHlSd6YBPwEIIgLhLFxJZAoZAgU6zBgWnCzlHnWKNrSZAocZB9TCpdck8ijJVjSgTCZB7SBf7VvdjT4JQpnBL99bSuXeiIh498aV9zkRR7nrNsqvT9VhYnFoIZAnybspt7jO7FdWuy1qeAJnrWjl9KNowKLBgz6yddtuoWEZAsngef1seSY0liZCtZCkfvBG6744RvngZD"
ad_account_id = "act_567906076722542"
pixel_id = "872436769567154"

[users]
[users.admin]
password = "admin123"
pages = "['Página Inicial', 'Matrículas', 'Financeiro', 'Análise GA', 'Análise Facebook']"

[users.usuario]
password = "senha123"
pages = "['Página Inicial', 'Matrículas']"

[users.ulisses]
password = "123"
pages = "['all']"

[users.vendedor]
password = "vendas_password"
pages = "['Oportunidades', 'Tendencias', 'Matriculas']"

[users.financeiro]
password = "fin_password"
pages = "['Financeiro', 'Cancelamentos']"

[database]
user = "seducar-readonly"
password = "C2A9lfa#_-rIG0#=sE0W"
host = "seducar-api-prod.compeceogyzg.us-east-2.rds.amazonaws.com"
port = "3306"
db_name = "seducar"

GCP_SERVICE_ACCOUNT_FILE = "gcp_credentials.json"